name: test deploy automation

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: "testing the github action automation to run index"
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test-job"
  test-job:
    # The type of runner that the job will run on
    runs-on: uat-ec2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: feature/pd-288-gihub-action

      - name: List directory
        run: |
          ls -ltr ${{ github.workspace }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: running template script
        run: bash ${{ github.workspace }}/indexes/autocomplete/dev/01-create_template.sh

      - name: running index script
        run: bash ${{ github.workspace }}/indexes/autocomplete/dev/02-create_index.sh

      - name: running policy script
        run: bash ${{ github.workspace }}/indexes/autocomplete/dev/03-index-policy.sh

      - run: echo "This job's status is ${{ job.status }}."
